[tox]
envlist = py{39,312}-lint, py{39,312}-molecule-create
minversion = 4.32.0
skipsdist = true

[testenv]
description = run the tests with pytest
skip_install = true

[testenv:py312-molecule-create]
allowlist_externals = 
    bash
    which
    pwd

deps =
    ansible==11.3.0
    molecule==25.1.0
    molecule-plugins==23.7.0
    molecule-plugins[docker,vagrant]
    setuptools
    please-cli
    rich
    testinfra
    bashlint

commands =
    pwd
    which python3
    python3 --version
    which ansible
    ansible --version
    which molecule
    molecule --version
    bash -c "export $(cat ~/.credentials/ansible_molecule.env | xargs) && molecule reset"
    bash -c "export $(cat ~/.credentials/ansible_molecule.env | xargs) && molecule create"

[testenv:py312-molecule-converge]
allowlist_externals = 
    bash

deps =
    ansible==11.3.0
    molecule==25.1.0
    molecule-plugins==23.7.0
    molecule-plugins[docker,vagrant]
    setuptools
    please-cli
    rich
    testinfra
    bashlint

commands =
    bash -c "export $(cat ~/.credentials/ansible_molecule.env | xargs) && molecule converge"

[testenv:py312-molecule-destroy]
allowlist_externals = 
    bash

deps =
    ansible==11.3.0
    molecule==25.1.0
    molecule-plugins==23.7.0
    molecule-plugins[docker,vagrant]
    setuptools
    please-cli
    rich
    testinfra
    bashlint

commands =
    bash -c "export $(cat ~/.credentials/ansible_molecule.env | xargs) && molecule destroy"
