---
- name: "OS Common - Debian Family - Packages - Debug Informations"
  ansible.builtin.debug:
    msg:
      - "========== Ansible Facts ============================================="
      - "ansible_os_family: {{ ansible_os_family | default('') }}"
      - "ansible_distribution: {{ ansible_distribution | default('') }}"
      - "ansible_distribution_release: {{ ansible_distribution_release | default('') }}"
      - "ansible_distribution_major_version: {{ ansible_distribution_major_version | default('') }}"
      - "ansible_distribution_version: {{ ansible_distribution_version | default('') }}"
      - "ansible_pkg_mgr: {{ ansible_pkg_mgr | default('') }}"
      - "========== Role Technical Variables (__os_common_*) =================="
      - "__os_common_repositories_retry (Task default 5): {{ __os_common_repositories_retry | default('') }}"
      - "__os_common_repositories_delay (Task default 10): {{ __os_common_repositories_delay | default('') }}"
      - "__os_common_package_manager_backend: {{ __os_common_package_manager_backend | default('') }}"
      - "__os_common_packages_manage: {{ __os_common_packages_manage | default('') }}"
      - "__os_common_packages: {{ __os_common_packages | default([]) }}"
      - "========== Role Variables ( os_common vars) =========================="
      - "os_common.packages_manage: {{ os_common.packages_manage | default('') }}"
      - "os_common.packages: {{ os_common.packages | default([]) }}"
      - "======================================================================"
    verbosity: "{{ os_common_debug_level | default(2) }}"
  tags:
    - os_common
    - os_common_packages
    - os_common_packages_debug
    - os_common_debian
    - os_common_debian_packages
    - os_common_debian_packages_debug

- name: "OS Common - Debian Family - Packages - Vars"
  ansible.builtin.set_fact:
    _packages_manage: "{{ os_common.packages_manage | default(true) or __os_common_packages_manage | default(true) }}"
    _packages: "{{ ((os_common.packages | default([])) + (__os_common_packages | default([]))) | unique }}"
  tags:
    - os_common
    - os_common_packages
    - os_common_packages_vars
    - os_common_debian
    - os_common_debian_packages
    - os_common_debian_packages_vars

- name: "OS Common - Debian Family - Packages - Vars - Debug Informations"
  ansible.builtin.debug:
    msg:
      - "================= Packages Vars ======================================"
      - "_packages_manage: {{ _packages_manage | default('') }}"
      - "_packages: {{ _packages | default([]) }}"
      - "======================================================================"
    verbosity: "{{ os_common_debug_level | default(3) }}"
  tags:
    - os_common
    - os_common_packages
    - os_common_packages_debug
    - os_common_debian
    - os_common_debian_packages
    - os_common_debian_packages_vars
    - os_common_debian_packages_vars_debug

- name: "OS Common - Debian Family - Packages- flush_handlers"
  ansible.builtin.meta: flush_handlers

- name: "OS Common - Redhat Family - Packages - Package - Loop"
  ansible.builtin.include_tasks: debian_package.yml
  loop: "{{ _packages }}"
  loop_control:
    loop_var: package
  when:
    - _packages_manage | default(true)
    - _packages | default([]) | length > 0 
  tags:
    - os_common
    - os_common_packages
    - os_common_debian
    - os_common_debian_packages
    - os_common_debian_packages_package
    - os_common_debian_packages_package_loop
...
