---
- name: "OS Common - Debian Family - Packages - Package - Debug Informations: {{ package.name | default('') }}"
  ansible.builtin.debug:
    msg:
      - "package: {{ package | default('') }}"
    verbosity: "{{ os_common_debug_level | default(3) }}"
  tags:
    - os_common
    - os_common_packages
    - os_common_packages_debug
    - os_common_debian
    - os_common_debian_packages
    - os_common_debian_packages_debug

- name: "OS Common - Debian Family - Packages - Package - Ensure debconf Preseed: {{ package.name | default('') }}"
  ansible.builtin.debconf:
    name: "{{ debconf.name }}"
    question: "{{ debconf.question | default(omit) }}"
    unseen: "{{ debconf.unseen | default(omit) }}"
    value: "{{ debconf.value | default(omit) }}"
    vtype: "{{ debconf.vtype | default(omit) }}"
  loop: "{{ package.debconf }}"
  loop_control:
    loop_var: debconf
  register: debconf_result
  when:
    - ( package.manage | default(true) )
    - ( package | default([]) | length > 0 )
    - ( package.debconf | default([]) | length > 0 )
  tags:
    - os_common
    - os_common_packages
    - os_common_packages_debug
    - os_common_debian
    - os_common_debian_packages
    - os_common_debian_packages_debconf

- name: "OS Common - Debian Family - Packages - Package - Ensure: {{ package.name | default('') }}"
  ansible.builtin.apt:
    allow_change_held_packages: "{{ package.allow_change_held_packages | default(omit) }}"
    allow_downgrade: "{{ package.allow_downgrade | default(omit) }}"
    allow_unauthenticated: "{{  package.allow_unauthenticated | default(omit) }}"
    auto_install_module_deps: "{{ package.auto_install_module_deps | default(omit) }}"
    autoclean: "{{ package.autoclean | default(omit) }}"
    autoremove: "{{ package.autoremove | default(omit) }}"
    cache_valid_time: "{{ package.cache_valid_time | default(omit) }}"
    clean: "{{ package.clean | default(omit) }}"
    deb: "{{ package.deb | default(omit) }}"
    default_release: "{{ package.default_release | default(omit) }}"
    dpkg_options: "{{ package.dpkg_options | default(omit) }}"
    fail_on_autoremove: "{{ package.fail_on_autoremove | default(omit) }}"
    force: "{{ package.force | default(omit) }}"
    force_apt_get: "{{ package.force_apt_get | default(omit) }}"
    install_recommends: "{{ package.install_recommends | default(omit) }}"
    lock_timeout: "{{ package.lock_timeout | default(omit) }}"
    name: "{{ package.name | default(omit) }}"
    only_upgrade: "{{ package.only_upgrade | default(omit) }}"
    policy_rc_d: "{{ package.policy_rc_d | default(omit) }}"
    purge: "{{ package.purge | default(omit) }}"
    state: "{{ package.state | default(omit) }}"
    update_cache: "{{ package.update_cache | default(omit) }}"
    update_cache_retries: "{{ __os_common_repositories_retry | default(5) }}"
    update_cache_retry_max_delay: "{{ __os_common_repositories_delay | default(10) }}"
    upgrade: "{{ package.upgrade | default(omit) }}"
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: apt_res
  retries: "{{ __os_common_packages_retry | default(5) }}"
  delay: "{{ __os_common_packages_delay | default(10) }}"
  until: apt_res is success
  when:
    - ( package.manage | default(true) )
    - ( package | default([]) | length > 0 )
  tags:
    - os_common
    - os_common_packages
    - os_common_packages_ensure
    - os_common_packages_ensure_unauthenticated
    - os_common_debian
    - os_common_debian_packages
    - os_common_debian_packages_ensure


- name: "OS Common - Debian Family - Packages - Package - Check if reboot needed: {{ package.name | default('') }}"
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  tags:
    - os_common
    - os_common_packages
    - os_common_packages_ensure
    - os_common_packages_ensure_unauthenticated
    - os_common_debian
    - os_common_debian_packages
    - os_common_debian_packages_reboot_ensure

- name: "OS Common - Debian Family - Packages - Package - Debug reboot: {{ package.name | default('') }}"
  ansible.builtin.debug:
    msg:
      - "reboot_required_file.stat.exists: {{ reboot_required_file.stat.exists | default('') }}"
      - "package: {{ package | default([]) }}"
    verbosity: "{{ os_common_debug_level | default(0) }}"
  when:
    - ( package.manage | default(true) )
    - ( package | default([]) | length > 0 )
    - ( reboot_required_file |  default([]) | length > 0 )
  tags:
    - os_common
    - os_common_packages
    - os_common_packages_ensure
    - os_common_packages_ensure_unauthenticated
    - os_common_debian
    - os_common_debian_packages
    - os_common_debian_packages_reboot_debug

- name: "OS Common - Debian Family - Packages - Package - Ensure reboot if needed: {{ package.name | default('') }}"
  ansible.builtin.reboot:
    reboot_timeout: 600   # attendre jusqu'à 10 minutes
    test_command: whoami  # commande pour tester si le serveur est prêt
  when:
    - ( package | default([]) | length > 0 )
    - ( package.manage | default(true) )
    - ( (package.reboot | default(false)) or (reboot_required_file.stat.exists | default(false)) )
  tags:
    - os_common
    - os_common_packages
    - os_common_packages_ensure
    - os_common_packages_ensure_unauthenticated
    - os_common_debian
    - os_common_debian_packages
    - os_common_debian_packages_reboot
...
