---
- name: "OS Common - Debian Family - Repositories - Debug Informations"
  ansible.builtin.debug:
    msg:
      - "========== Ansible Facts ============================================="
      - "ansible_os_family: {{ ansible_os_family | default('') }}"
      - "ansible_distribution: {{ ansible_distribution | default('') }}"
      - "ansible_distribution_release: {{ ansible_distribution_release | default('') }}"
      - "ansible_distribution_major_version: {{ ansible_distribution_major_version | default('') }}"
      - "ansible_distribution_version: {{ ansible_distribution_version | default('') }}"
      - "ansible_pkg_mgr: {{ ansible_pkg_mgr | default('') }}"
      - "========== Role Technical Variables (__os_common_*) =================="
      - "__os_common_repositories_manage: {{ __os_common_repositories_manage | default('') }}"
      - "__os_common_repositories: {{ __os_common_repositories | default([]) }}"
      - "__os_common_repositories_retry: {{ __os_common_repositories_retry | default('') }}"
      - "__os_common_repositories_delay: {{ __os_common_repositories_delay | default('') }}"
      - "========== Role Variables ( os_common vars) =========================="
      - "os_common.repositories_manage: {{ os_common.repositories_manage | default('') }}"
      - "os_common.repositories: {{ os_common.repositories | default([]) }}"
      - "========== Role Variables ( os_common vars) =========================="
    verbosity: "{{ os_common_debug_level | default(2) }}"
  tags:
    - os_common
    - os_common_repositories
    - os_common_debian
    - os_common_debian_repositories
    - os_common_debian_repositories_debug

- name: "OS Common - Debian Family - Repositories - Merge internal and external variables"
  ansible.builtin.set_fact:
    _repositories_manage: "{{ (__os_common_repositories_manage | default(true)) or (os_common.repositories_manage | default(true)) }}"
    _repositories: "{{ ((__os_common_repositories | default([])) + (os_common.repositories | default([]))) | unique }}"
  tags:
    - os_common
    - os_common_repositories
    - os_common_debian
    - os_common_debian_repositories
    - os_common_debian_repositories_vars

- name: "OS Common - Debian Family - Repositories - Compute Variables - debug"
  ansible.builtin.debug:
    msg:
      - "================= Repositories Vars =================================="
      - "_repositories_manage: {{ _repositories_manage | default('') }}"
      - "_repositories: {{ _repositories | default([]) }}"
      - "========== Role Variables ( os_common vars) =========================="
    verbosity: "{{ os_common_debug_level | default(3) }}"
  tags:
    - os_common
    - os_common_repositories
    - os_common_debian
    - os_common_debian_repositories
    - os_common_debian_repositories_vars_debug

- name: "OS Common - Debian Family - Repositories - Ensure Repositories"
  ansible.builtin.include_tasks: debian_repository.yml
  loop: "{{ _repositories }}"
  loop_control:
    loop_var: repository
  when:
    - _repositories | default([]) | length > 0
    - _repositories_manage is not defined or _repositories_manage is boolean
    - _repositories_manage | default(true)
  tags:
    - os_common
    - os_common_repositories
    - os_common_debian
    - os_common_debian_repositories
    - os_common_debian_repositories_repository
    - os_common_debian_repositories_repository_loop

...
