---
- name: "OS Common - Hosts File - Debug Informations: {{ os_common.hosts.file | default('/etc/hosts') }}"
  ansible.builtin.debug:
    msg:
      - "os_common.hosts: {{ os_common.hosts | default([]) }}"
    verbosity: "{{ os_common_debug_level | default(3) }}"
  tags:
    - os_common
    - os_common_hosts
    - os_common_hosts_debug

- name: "OS Common - Hosts File - Ensure: {{ os_common.hosts.file | default('/etc/hosts') }}"
  ansible.builtin.lineinfile:
    path: "{{ os_common.hosts.file | default('/etc/hosts') }}"
    line: "{{ hosts_line }}"
    state: present
  loop: "{{ os_common.hosts.lines }}"
  loop_control:
    loop_var: hosts_line
  register: hosts_result
  when:
    - ( os_common.hosts | default([]) | length > 0 )
    - ( os_common.hosts_manage | default(true) )
    - ( os_common.hosts.lines | default([]) | length > 0 )
  tags:
    - os_common
    - os_common_debug
    - os_common_hostname
    - os_common_hostname_ensure

...
