---
# Variable OS Family specific.
- name: Include OS Family specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - os_common
    - os_common_vars
    - os_common_vars_load
    - os_common_vars_load_os_family

# Variable OS distribution version specific.
- name: Include OS Debian Family distributions version specific Variables.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:
    - ansible_os_family == 'Debian'
  tags:
    - os_common
    - os_common_vars
    - os_common_vars_load
    - os_common_vars_load_distribution
    - os_common_vars_load_distribution_debian

- name: Include OS RHEL Family distributions version specific Variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'
    - ansible_distribution != 'Amazon'
    - ansible_distribution != 'Rocky'
    - ansible_distribution != 'AlmaLinux'
  tags:
    - os_common
    - os_common_vars
    - os_common_vars_load
    - os_common_vars_load_distribution
    - os_common_vars_load_distribution_redhat

- name: Include OS Rocky Distributions version specific Variables.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:
    - ansible_distribution == 'Rocky'
  tags:
    - os_common
    - os_common_vars
    - os_common_vars_load
    - os_common_vars_load_distribution
    - os_common_vars_load_distribution_rocky

- name: Include OS AlmaLinux Distributions version specific Variables.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:
    - ansible_distribution == 'AlmaLinux'
  tags:
    - os_common
    - os_common_vars
    - os_common_vars_load
    - os_common_vars_load_distribution
    - os_common_vars_load_distribution_almalinux

- name: Include OS Amazon Distributions version specific Variables.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when:
    - ansible_distribution == 'Amazon'
  tags:
    - os_common
    - os_common_vars
    - os_common_vars_load
    - os_common_vars_load_distribution
    - os_common_vars_load_distribution_amazon

- name: Include OS CentOS Distributions version specific Variables.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when:
    - ansible_distribution == 'CentOS'
  tags:
    - os_common
    - os_common_vars
    - os_common_vars_load
    - os_common_vars_load_distribution
    - os_common_vars_load_distribution_amazon

...
