---
- name: "OS Common - Redhat Family - Repositories - Manage Repositories - Repository - Debug Informations - {{ repository.name | default('') }}"
  ansible.builtin.debug:
    msg:
      - "ansible_pkg_mgr: {{ ansible_pkg_mgr | default('') }}"
      - "__os_common_package_manager_backend: {{ __os_common_package_manager_backend | default('') }}"
      - "__os_common_repositories_manage: {{ __os_common_repositories_manage | default(false) }}"
      - "repositories_file.file : {{ repositories_file.file | default('') }}"
      - "repository: {{ repository | default([]) }}"
    verbosity: "{{ os_common_debug_level | default(1) }}"
  tags:
    - os_common
    - os_common_repositories
    - os_common_repositories_debug
    - os_common_rhel
    - os_common_rhel_repositories
    - os_common_rhel_repositories_debug
    - os_common_rhel_repositories_repositories_files
    - os_common_rhel_repositories_repositories_files_repositories_file
    - os_common_rhel_repositories_repositories_files_repositories_file_repository

- name: "OS Common - Redhat Family - Repositories - Manage Repositories - Repository - Ensure Repository - {{ repository.name | default('') }}"
  ansible.builtin.yum_repository:
    name: "{{ repository.name }}"
    description: "{{ repository.description | default(omit) }}"
    file: "{{ repositories_file.file | default(omit) }}"
    baseurl: "{{ repository.baseurl | default(omit) }}"
    enabled: "{{ repositories_file.file | default(omit) }}"
    gpgcheck: "{{ repositories_file.file | default(omit) }}"
    gpgkey: "{{ repositories_file.file | default(omit) }}"
  tags:
    - os_common
    - os_common_repositories
    - os_common_repositories_debug
    - os_common_rhel
    - os_common_rhel_repositories
    - os_common_rhel_repositories_debug
    - os_common_rhel_repositories_repositories_files
    - os_common_rhel_repositories_repositories_files_repositories_file
    - os_common_rhel_repositories_repositories_files_repositories_file_repository
...
