---
- name: "OS Common - Redhat Family - Repositories"
  ansible.builtin.import_tasks: rhel_manage_repositories.yml
  tags:
    - os_common
    - os_common_repositories
    - os_common_rhel
    - os_common_rhel_manage_repositories

- name: OS Common - Redhat Family - Packages
  ansible.builtin.import_tasks: rhel_packages.yml
  tags:
    - os_common
    - os_common_packages
    - os_common_rhel
    - os_common_rhel_packages

- name: OS Common - Redhat Family - Groups
  ansible.builtin.import_tasks: groups.yml
  tags:
    - os_common
    - os_common_groups
    - os_common_rhel
    - os_common_rhel_groups

- name: OS Common - Redhat Family - Users
  ansible.builtin.import_tasks: users.yml
  tags:
    - os_common
    - os_common_users
    - os_common_rhel
    - os_common_rhel_users

- name: OS Common - Redhat Family - Directories
  ansible.builtin.import_tasks: directories.yml
  tags:
    - os_common
    - os_common_directories
    - os_common_rhel
    - os_common_rhel_directories

- name: "OS Common - Redhat Family - LVM"
  ansible.builtin.import_tasks: lvm.yml
  tags:
    - os_common
    - os_common_lvms
    - os_common_rhel
    - os_common_rhel_lvms

...
