---
- name: "OS Common - Handlers - Yum - Update cache"
  ansible.builtin.yum:
    update_cache: true
  retries: "{{ __os_common_repositories_retry | default('5') }}"
  delay: "{{ __os_common_repositories_delay | default('10') }}"
  register: yum_update_res
  until: yum_update_res is success
  when:
    - (__os_common_package_manager | default(ansible_pkg_mgr)) == 'yum'
  listen: "Update rhel repository cache"
  tags:
    - os_common
    - os_common_handlers
    - os_common_handlers_update_repository_cache
    - os_common_handlers_yum_update_cache

- name: "OS Common - Handlers - DNF - Update cache"
  ansible.builtin.dnf:
    update_cache: true
  retries: "{{ __os_common_repositories_retry | default('5') }}"
  delay: "{{ __os_common_repositories_delay | default('10') }}"
  register: dnf_update_res
  until: dnf_update_res is success
  when:
    - (__os_common_package_manager | default(ansible_pkg_mgr)) == 'dnf' or (__os_common_package_manager | default(ansible_pkg_mgr)) == 'dnf5'
  listen: "Update rhel repository cache"
  tags:
    - os_common
    - os_common_handlers
    - os_common_handlers_update_repository_cache
    - os_common_handlers_yum_update_cache

- name: "OS Common - Handlers - APT - Update cache"
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    allow_unauthenticated: true
    cache_valid_time: 0
    #dpkg_options: "force-confdef,force-confold"
  retries: "{{ __os_common_repositories_retry | default('5') }}"
  delay: "{{ __os_common_repositories_delay | default('10') }}"
  register: apt_update_res
  until: apt_update_res is success
  when:
    - (__os_common_package_manager | default(ansible_pkg_mgr)) == 'apt'
  listen: "Update debian repository cache"
  tags:
    - os_common
    - os_common_handlers
    - os_common_handlers_update_repository_cache
    - os_common_handlers_yum_update_cache


- name: "OS Common - Handlers - Ensure Directories"
  ansible.builtin.include_tasks: directory.yml
  loop: "{{ os_common.directories | default([], true) }}"
  loop_control:
    loop_var: directory
  when:
    - os_common.directories_manage | default(false)
    - os_common.directories
  listen: "Ensure Directories"
  tags:
    - os_common
    - os_common_handlers
    - os_common_handlers_directories
    - os_common_handlers_directories_ensure
